# Generated by Django 2.2.6 on 2019-10-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_auto_20191014_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('PO_num', models.CharField(max_length=10)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateTimeField(auto_now=True)),
                ('received_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('buy_or_rent', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=4)),
                ('comments', models.TextField(verbose_name=140)),
                ('entered_via', models.CharField(choices=[('O', 'Order'), ('I', 'Invoice'), ('R', 'Rental Slip')], max_length=2)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.Job')),
            ],
        ),
    ]
