# Generated by Django 2.2.6 on 2019-10-14 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20191014_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
    ]
