# Generated by Django 2.2.6 on 2019-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20191014_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
