# Generated by Django 2.2.6 on 2019-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20191014_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='comments',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
