# Generated by Django 2.2.6 on 2019-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='rate',
        ),
        migrations.AddField(
            model_name='equipment',
            name='day_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='month_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='week_rate',
            field=models.FloatField(default=0),
        ),
    ]
