# Generated by Django 2.2.6 on 2019-10-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20191014_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='retail_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Category'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Vendor'),
        ),
    ]
